### ISSUE TITLE
Memory overflow occurs when the file is large

### ISSUE THREAD

**Issue by toutoumu** [junrar/junrar#182]
**Describe the bug**
When I try to preview a large file, such as 1G, the memory will overflow.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**File**
If possible, please attach or provide a link to the RAR file.

**Environment (please complete the following information):**
 - OS: Android 13
 - Junrar version: 7.5.5

**Additional context**
The code used is as follows

```java
                        File f = loc.getCurrentPath().getFile();
                        InputStream stream = f.getInputStream();

                        archive = new Archive(stream);
                        fileListAdapter.setArchive(archive);
                        List<FileHeader> fileHeaders = archive.getFileHeaders();
                        TreeData<FileHeader> forest = new TreeData<>(null);
                        fileHeaders.forEach(FileHeader -> {
                            if (FileHeader != null) {
                                TreeData<FileHeader> temp = forest;
                                for (String data : FileHeader.getFileName().split("\\\\")) {
                                    temp = temp.addAndReturnChild(data);
                                }
                                temp.setData(FileHeader);
                            }
                        });

```

**Comment by gotson** [comment]
how much memory does your system has, and how do you start `java` ?

**Comment by toutoumu** [comment]
I run this program in my Android app, and I find that the rar file will be loaded into memory in its entirety before it can be randomly accessed, so when the file size is larger than the maximum size of my phone's memory (allocated to the App), an exception will occur.
The result I expect is that the app will only read the file from the disk when I need to read it, without writing it into the cache.

**Comment by gotson** [comment]
If you have a file on disk, you should use the `Archive(File file)` constructor instead, which uses `RandomAccessFile`.

I believe that the problem is Android does not let you access the file system directly, and would wrap everything, and make it available only in a stream. This is a problem, because the streams are not randomly accessible. RAR4 is build in a way that headers are not centrally located, but located before each file. Junrar needs to go through the whole file first, skipping the data parts, in order to get a list of the files. When you want to extract, the position must be set to a previous position, which is not possible if the stream is not seekable.

There's not much way around it unfortunately, the Android API makes it difficult to handle such cases.

**Comment by toutoumu** [comment]
I think I may have found a solution, I copied the code into the [edslite](https://github.com/sovworks/edslite) project and replaced java.io.File with com.igeltech.nevercrypt.fs.File and it worked.

**Comment by toutoumu** [comment]
I think I may have found a solution, I copied the code into the [edslite](https://github.com/sovworks/edslite) project and replaced java.io.File with com.igeltech.nevercrypt.fs.File and it worked.
