### ISSUE TITLE
Minimum needed Java version

### ISSUE THREAD

**Issue by theobisproject** [junrar/junrar#20]
I am a bit confused about which is the minimum Java version requirement for Junrar. The version in the pom.xml for the maven-compiler plugin is Java 6 (source and target) but the apache-vfs dependency states that the minimum Java version for 2.2 is Java 7 (see https://commons.apache.org/proper/commons-vfs/).
Was the version of apache-vfs raised on purpose to require Java 7 for Junrar and the changes for the maven-compiler-plugin forgotten or did this happen on accident?

**Comment by gotson** [comment]
I am looking at this now, I don't quite understand why there is VFS in the first place. I think it makes sense to remove it completely from the project. Do you have any view on that ?

I also plan to raise the minimum requirements to Java 8, since Java 6 is EOL and even the extended support has been dropped. Java 7 is still supported with extended support from Oracle until 2022, but now that Java 11 is LTS, and Java 8 is already considered legacy, a minimum of Java 8 should be more than enough.

**Comment by theobisproject** [comment]
First: I don't use the VFS integration but if it is there some people will definitely do. For me it's more a not needed dependency in the project.
I personally would think about extracting the vfs integration into his own submodule and publish a junrar-vfs.jar. So "core" RAR implementation doesn't have this dependency any more.

**Comment by gotson** [comment]
> First: I don't use the VFS integration but if it is there some people will definitely do. For me it's more a not needed dependency in the project.
> I personally would think about extracting the vfs integration into his own submodule and publish a junrar-vfs.jar. So "core" RAR implementation doesn't have this dependency any more.

Thanks, that is a good idea. I will create a separate issue and see how we can do that.
