### ISSUE TITLE
[BUG]Using inputStream to decompress some huge files causes OutOfMemoryError

### ISSUE THREAD

**Issue by WangWeiHuawwh** [junrar/junrar#60]
**Describe the bug**
Using inputStream to decompress some huge files causes OutOfMemoryError。

the code like：
InputSteam inputStream = new FileInputStream(file);
Archive arch = new Archive(inputSteam);

All code is run in thread，The reason seems to be readHeaders() method will never reach EndArcHeader on Archive.java.

**To Reproduce**
NA

**Expected behavior**
NA

**File**
http://1pan.top/page/5fa5358d4243e72091c9c7c4
click:"获取下载链接"

**Environment (please complete the following information):**
 - OS: [Android Q/R]
 - Junrar version: [7.4.0]

**Additional context**

[](url)

**Comment by gotson** [comment]
It's not a bug, but a limitation from the library.

In order to read a RAR file, we need random access, as the headers are spread between the actual encoded files. To that end, when you create an `Archive` from an `InputStream`, junrar uses a `RandomAccessInputStream` (see [here](https://github.com/junrar/junrar/blob/1931072e1213f283fe42b37a9ba540a95cbcca0e/src/main/java/com/github/junrar/io/RandomAccessInputStream.java)), which is backed by a memory cache.

You probably don't have enough memory for the cache of the `RandomAccessInputStream` to effectively store the 500mb of your file.

If you were to use `Archive` from a `File`, junrar would instead use `RandomAccessFile`, which wouldn't load the whole file in memory.

If you can switch to using a `File` instead of a `InputStream`, i would recommend you do so. From the sample code you provided, it seems you have a `File` already, so it should be easy to change.

**Comment by WangWeiHuawwh** [comment]
The above code is just a Demo，Actually I only have uri parameter，and can only use uri conversion to InputStream to decompress. do you have a good ideal?

**Comment by gotson** [comment]
The only way would be to store the file on disk temporarily, and use a `File` thereafter.

Using a Uri and à stream would anyhow end up downloading the full file, so if you can download on disk instead of memory, that should work.
